name : Main Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  initJob:
    uses : ./.github/workflows/goscrap.yaml
    with:
      targetRepo: anuragkanwar/docus
      sitemapPath: http://localhost:3000/sitemap.xml
      configPath: ./js.json
    secrets:
      apiKey: ${{ secrets.API_KEY }}

  p1:
    needs: initJob
    uses : ./.github/workflows/goscrap.yaml
    with:
      targetRepo: anuragkanwar/docus
      sitemapPath: http://localhost:3000/sitemap.xml
      configPath: ./js.json
    secrets:
      apiKey: ${{ secrets.API_KEY }}
  p2:
    needs : initJob
    uses : ./.github/workflows/goscrap.yaml
    with:
      targetRepo: anuragkanwar/docus
      sitemapPath: http://localhost:3000/sitemap.xml
      configPath: ./js.json
    secrets:
      apiKey: ${{ secrets.API_KEY }}
  p3:
    needs : initJob
    uses : ./.github/workflows/goscrap.yaml
    with:
      targetRepo: anuragkanwar/docus
      sitemapPath: http://localhost:3000/sitemap.xml
      configPath: ./js.json
    secrets:
      apiKey: ${{ secrets.API_KEY }}
  p4:
    needs: initJob
    uses : ./.github/workflows/goscrap.yaml
    with:
      targetRepo: anuragkanwar/docus
      sitemapPath: http://localhost:3000/sitemap.xml
      configPath: ./js.json

    secrets:
      apiKey: ${{ secrets.API_KEY }}
  p5:
    needs : initJob
    uses : ./.github/workflows/goscrap.yaml
    with:
      targetRepo: anuragkanwar/docus
      sitemapPath: http://localhost:3000/sitemap.xml
      configPath: ./js.json
    secrets:
      apiKey: ${{ secrets.API_KEY }}
  p6:
    needs : initJob
    uses : ./.github/workflows/goscrap.yaml
    with:
      targetRepo: anuragkanwar/docus
      sitemapPath: http://localhost:3000/sitemap.xml
      configPath: ./js.json
      fail : true
    secrets:
      apiKey: ${{ secrets.API_KEY }}


  final_job:
    needs : [p1, p2, p3, p4, p5, p6]
    uses : ./.github/workflows/goscrap.yaml
    with:
      targetRepo: anuragkanwar/docus
      sitemapPath: http://localhost:3000/sitemap.xml
      configPath: ./js.json
    secrets:
      apiKey: ${{ secrets.API_KEY }}

  notify_job:
    needs: [initJob, p1, p2, p3, p4, p5, p6, final_job]
    runs-on: ubuntu-latest
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name : dump needs
        run : |
          echo '${{ toJson(needs) }}'
      - name : custom script
        uses: actions/github-script@v7
        with:
          script : |
            const val = "${{ needs }}"
            console.log(val)

      - name : send slack message
        run : |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"workflow failed @kmitr "}' ${{ secrets.SLACK_WEBHOOK_URL }}

