name : Run Go and Docusaurus

on:
  workflow_call:
    inputs:
      targetRepo:
        description: Target Docs repository
        type: string
        required: true
      sitemapPath:
        description: Target Docs repository
        type: string
        required: true
      configPath:
        description: Target Docs repository
        type: string
        required: true
      fail:
        description: should fail or not
        type: boolean
        required: false
        default: false
    secrets:
      apiKey:
        description: Api key
        required: true
jobs:
  build-and-run:
    runs-on : ubuntu-latest
    steps:
      - name: check should fail
        if : ${{ inputs.fail == true }}
        run : |
          echo "::error fail set to true"
          exit 1
      - uses : actions/checkout@v4
        with :
          repository : anuragkanwar/go-sc
          fetch-depth : 0
          path : "./go-sc"
      - uses: actions/checkout@v4
        with :
          repository : ${{ inputs.targetRepo }}
          fetch-depth : 0
          path : "./docus"
      - name : Node
        uses : actions/setup-node@v4
        with :
          node-version: "20"
      - name: Build and Run React App
        run: |
          ls
          cd docus
          # npm install
          # npm run build
          # npm run serve --no-open &
      - name : Go
        uses: "actions/setup-go@v5"
        with:
          go-version: '1.23.3'
      - run: go version

      - name: Build Go server
        run: |
          cd go-sc
          go mod download all
          go build -o app

      - name : Run Go server
        run : |
          cd go-sc
          ./app ${{ inputs.sitemapPath }} ${{ inputs.configPath }} ${{ secrets.apiKey }}

